[main]
font=JetBrainsMono Nerd Font:size=13
dpi-aware=auto
prompt="> "

# Жестко задаем слой и привязку по центру, чтобы он не прыгал за курсором


width=30
lines=10
horizontal-pad=15
vertical-pad=15
inner-pad=10

# Отключаем поведение выбора мышью при наведении, если оно мешает
fields=name,generic,comment,exec,filename,keywords
match-mode=exact

[colors]
background=1a1b26ff
text=c0caf5ff
match=7aa2f7ff
selection=414868ff
selection-text=c0caf5ff
border=9d7cd8ff

[border]
width=2
radius=8
